In [544]:
import pandas as pd

In [545]:
#read Csv file as Data

In [546]:
df = pd.read_csv("pokemon.csv")

In [547]:
df.head(2)

   id       name  type1   type2  hp  attack  defense  speed
0   1  Bulbasaur  Grass  Poison  45      49       49     45
1   2    Ivysaur  Grass  Poison  60      62       63     60

In [548]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       9 non-null      int64
 1   name     9 non-null      str
 2   type1    9 non-null      str
 3   type2    4 non-null      str
 4   hp       9 non-null      int64
 5   attack   9 non-null      int64
 6   defense  9 non-null      int64
 7   speed    9 non-null      int64
dtypes: int64(5), str(3)
memory usage: 708.0 bytes

In [549]:
new_df = df[df['hp']>69]

In [550]:
new_df.shape

(3, 8)

In [551]:
df [(df['hp']>=70) & (df['attack']>=80)]

   id       name  type1   type2  hp  attack  defense  speed
2   3   Venusaur  Grass  Poison  80      82       83     80
5   6  Charizard   Fire  Flying  78      84       78    100
8   9  Blastoise  Water     NaN  79      83      100     78

In [552]:
new_df1 = df [(df['hp']>=70) | (df['attack']>=80)]

In [553]:
new_df1.head()

   id       name  type1   type2  hp  attack  defense  speed
2   3   Venusaur  Grass  Poison  80      82       83     80
5   6  Charizard   Fire  Flying  78      84       78    100
8   9  Blastoise  Water     NaN  79      83      100     78

In [554]:
new_df2 =df [(df['speed']>=80) & (df['attack']<=100)]

In [555]:
new_df2.head()

   id        name  type1   type2  hp  attack  defense  speed
2   3    Venusaur  Grass  Poison  80      82       83     80
4   5  Charmeleon   Fire     NaN  58      64       58     80
5   6   Charizard   Fire  Flying  78      84       78    100

In [556]:
#filter columns

In [557]:
df.columns

Index(['id', 'name', 'type1', 'type2', 'hp', 'attack', 'defense', 'speed'], dtype='str')

In [558]:
df [['name', 'type1' , 'hp']]

         name  type1  hp
0   Bulbasaur  Grass  45
1     Ivysaur  Grass  60
2    Venusaur  Grass  80
3  Charmander   Fire  39
4  Charmeleon   Fire  58
5   Charizard   Fire  78
6    Squirtle  Water  44
7   Wartortle  Water  59
8   Blastoise  Water  79

In [559]:
df [['name', 'type1', 'attack', 'speed']]

         name  type1  attack  speed
0   Bulbasaur  Grass      49     45
1     Ivysaur  Grass      62     60
2    Venusaur  Grass      82     80
3  Charmander   Fire      52     65
4  Charmeleon   Fire      64     80
5   Charizard   Fire      84    100
6    Squirtle  Water      48     43
7   Wartortle  Water      63     58
8   Blastoise  Water      83     78

In [560]:
df[(df['attack']>80) & (df['speed']<=100)] [['name', 'type1', 'attack','speed']]

        name  type1  attack  speed
2   Venusaur  Grass      82     80
5  Charizard   Fire      84    100
8  Blastoise  Water      83     78

In [561]:
#exact value - loc iloc

In [562]:
df.loc[0:3,"name" : "defense"]

         name  type1   type2  hp  attack  defense
0   Bulbasaur  Grass  Poison  45      49       49
1     Ivysaur  Grass  Poison  60      62       63
2    Venusaur  Grass  Poison  80      82       83
3  Charmander   Fire     NaN  39      52       43

In [563]:
df.loc[0:3,"type2" :]

    type2  hp  attack  defense  speed
0  Poison  45      49       49     45
1  Poison  60      62       63     60
2  Poison  80      82       83     80
3     NaN  39      52       43     65

In [564]:
df.loc[0:3,["attack","type1", "name"]]

   attack  type1        name
0      49  Grass   Bulbasaur
1      62  Grass     Ivysaur
2      82  Grass    Venusaur
3      52   Fire  Charmander

In [565]:
df.loc[4, 'name'] = 'newname'

In [566]:
df.head()

   id        name  type1   type2  hp  attack  defense  speed
0   1   Bulbasaur  Grass  Poison  45      49       49     45
1   2     Ivysaur  Grass  Poison  60      62       63     60
2   3    Venusaur  Grass  Poison  80      82       83     80
3   4  Charmander   Fire     NaN  39      52       43     65
4   5     newname   Fire     NaN  58      64       58     80

In [567]:
df.iloc[0:5, 0:3]

   id        name  type1
0   1   Bulbasaur  Grass
1   2     Ivysaur  Grass
2   3    Venusaur  Grass
3   4  Charmander   Fire
4   5     newname   Fire

In [568]:
df.loc[0:5,]

   id        name  type1   type2  hp  attack  defense  speed
0   1   Bulbasaur  Grass  Poison  45      49       49     45
1   2     Ivysaur  Grass  Poison  60      62       63     60
2   3    Venusaur  Grass  Poison  80      82       83     80
3   4  Charmander   Fire     NaN  39      52       43     65
4   5     newname   Fire     NaN  58      64       58     80
5   6   Charizard   Fire  Flying  78      84       78    100

In [569]:
df['type1'].value_counts()

type1
Grass    3
Fire     3
Water    3
Name: count, dtype: int64

In [570]:
df['type1'].unique

<bound method Series.unique of 0    Grass
1    Grass
2    Grass
3     Fire
4     Fire
5     Fire
6    Water
7    Water
8    Water
Name: type1, dtype: str>

In [571]:
df['type2'].value_counts()

type2
Poison    3
Flying    1
Name: count, dtype: int64